#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dillinger"
name = "Dillinger"
description.en = "Documentation tool for creativity"
description.fr = "Outil de documentation pour la créativité"

version = "11.1.3~ynh3"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://dodoc.fr/"
demo = "https://test.dodoc.fr/"
admindoc = "https://github.com/l-atelier-des-chercheurs/dodoc#readme"
code = "https://github.com/l-atelier-des-chercheurs/dodoc"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "512M"
ram.build = "1000M"
ram.runtime = "512M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]

    url = "https://github.com/joemccann/dillinger/archive/refs/tags/3.5.1.tar.gz"
    sha256 = "89cb348031e949b24ea38368da657bab2c3a030508dcaafd0a46697931656bcc"

    #autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]

    [resources.apt]
    packages = [
    "ffmpeg",
    "build-essential",
    "libjpeg-dev",
    "libgif-dev",
    "libgconf-2-4",
    "libpango1.0-dev",
    "libc6",
    "libnss3",
    "librsvg2-dev",
    "libxcomposite1",
    "libasound2",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcairo2",
    "libcairo2-dev",
    "libcups2",
    "libdbus-1-3",
    "libexpat1",
    "libfontconfig1",
    "libgbm1",
    "libgcc1",
    "libglib2.0-0",
    "libgtk-3-0",
    "libnspr4",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libstdc++6",
    "libx11-6",
    "libx11-xcb1",
    "libxcb1",
    "libxcomposite1",
    "libxcursor1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxi6",
    "libxrandr2",
    "libxrender1",
    "libxss1",
    "libxtst6",
    "xdg-utils",
    "lsb-release",
    "wget"
    ]
